apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: postgres
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432
status:
  loadBalancer:
    ingress:
# <some ip or existing ip resource>
